xp5:
  description: "XP Framework"
  tree:
    ".":
      - xp.public: git@github.com:xp-framework/xp-framework.git
      - compiler: git@github.com:xp-lang/compiler.git

kiesel:
  description: "Private projects"
  tree:
    ".":
      - dialog: git@github.com:thekid/dialog.git

xp6:
  description: "XP Framework 6-line"
  tree:
    "xp6":
      - core: git@github.com:xp-framework/core.git
      - codegen: git@github.com:xp-framework/codegen.git
      - csv: git@github.com:xp-framework/csv.git
      - doclet: git@github.com:xp-framework/doclet.git
      - glue: git@github.com:xp-framework/glue.git
      - http: git@github.com:xp-framework/http.git
      - imaging: git@github.com:xp-framework/imaging.git
      - inject: git@github.com:xp-forge/inject.git
      - ldap: git@github.com:xp-framework/ldap.git
      - mail: git@github.com:xp-framework/mail.git
      - parser: git@github.com:xp-framework/parser.git
      - rdbms: git@github.com:xp-framework/rdbms.git
      - rest: git@github.com:xp-framework/rest.git
      - scriptlet: git@github.com:xp-framework/scriptlet.git
      - sequence: git@github.com:xp-forge/sequence.git
      - web: git@github.com:xp-framework/web.git
      - webservices: git@github.com:xp-framework/webservices.git
      - xml: git@github.com:xp-framework/xml.git
      - zip: git@github.com:xp-framework/zip.git
      # - ftp: git@github.com:xp-framework/ftp.git
      # - irc: git@github.com:xp-framework/irc.git
      # - news: git@github.com:xp-framework/news.git
      # - remote: git@github.com:xp-framework/remote.git
      # - sieve: git@github.com:xp-framework/sieve.git
      # - spelling: git@github.com:xp-framework/spelling.git
      # - telephony: git@github.com:xp-framework/telephony.git
      # - webdav: git@github.com:xp-framework/webdav.git

xp-forge:
  description: "XP Contrib"
  tree:
    "xp.forge":
      - stomp: git@github.com:xp-forge/stomp.git
      - handlebars: git@github.com:xp-forge/handlebars.git
      - mustache: git@github.com:xp-forge/mustache.git
      - yaml: git@github.com:xp-forge/yaml.git
      - markdown: git@github.com:xp-forge/markdown.git
      # - nsca: git@github.com:xp-forge/nsca.git

xp-infra:
  description: "XP Framework Infrastructure"
  tree:
    ".":
      - rfc: git@github.com:xp-framework/rfc.git
      - xp.runners: git@github.com:xp-framework/xp-runners.git
      - xp-maven-plugin: git@github.com:xp-forge/xp-maven-plugin.git

default:
  includes:
    - xp5
    - xp-infra
    - xp-forge
    - kiesel